name: buildroot-test

on:
  push:
    branches:
      - main

jobs:
  buildroot-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set BR2_EXTERNAL
        run: echo "BR2_EXTERNAL=/home/runner/work/assignment-4-patricereneeemery/assignment-4-patricereneeemery/base_external" >> $GITHUB_ENV

      - name: Build Buildroot
        run: |
          cd /home/runner/work/assignment-4-patricereneeemery/assignment-4-patricereneeemery/buildroot
          make aesd_defconfig
          make
